import { generateCodeLine } from './templates.js';

// Generate a complete, runnable Playwright script from parsed steps

export function generate(steps, options = {}) {
  const lines = steps.map((step, i) => generateCodeLine(step, i));

  const code = `// Generated by Runly — ${new Date().toISOString()}
// Command: ${options.rawInput || 'unknown'}

import { chromium, expect } from 'playwright';

(async () => {
  const browser = await chromium.launch({ headless: ${options.headless !== false} });
  const context = await browser.newContext();
  const page = await context.newPage();

  try {
${lines.join('\n\n')}

    console.log('\\n✓ All steps passed');
  } catch (error) {
    console.error('\\n✗ Test failed:', error.message);
    await page.screenshot({ path: 'runly-failure.png' });
    process.exitCode = 1;
  } finally {
    await context.close();
    await browser.close();
  }
})();
`;

  return code;
}
